### ISSUE TITLE
Bot crashes on st

### ISSUE THREAD

**Issue by Evileoo** [Alphatism/loquibot#6]
Bot crashes on start

Shows "updating 0%" and shut downs

**Comment by Alphalaneous** [comment]
This means something is blocking access to loquibot's servers on your PC or network. The only solution to that is either figuring out what is causing it on your end or using a VPN

**Comment by Evileoo** [comment]
I don't have VPN

Even executing it as administrator doesn't work

**Comment by Alphalaneous** [comment]
As I mentioned, this isn't an issue I can really solve right now, and is something to do with your network or computer blocking access to the loquibot servers. Running as administrator will not resolve something blocking a web request.

The only alternative in this case is to use a VPN such as ProtonVPN as it is free, open loquibot, then to prevent it from ever updating again, go to %appdata%/loquibot and edit version.txt to say `version=999`

**Comment by Evileoo** [comment]
The folder contains a `bin` and `jre` folder

But everything is empty

**Comment by Alphalaneous** [comment]
yes it will remain empty until you do the first step I said

**Comment by Evileoo** [comment]
I tried
The same thing occurs with the VPN

**Comment by Alphalaneous** [comment]
Then it must be something on the system level. Do you have any antiviruses?

**Comment by Evileoo** [comment]
Nope

**Comment by Alphalaneous** [comment]
Let's continue on the loquibot discord then.
