### ISSUE TITLE
Loquibot won't chat

### ISSUE THREAD

**Issue by ghost** [Alphatism/loquibot#7]
Recently in my livestreams, loquibot **isn't chatting**. It might be **outdated** but i don't know how to download a new update if there is one (and i have **silent chat mode off**)

**Comment by Alphalaneous** [comment]
Do you have a discord? If so, could you join the loquibot discord server so we can communicate?

**Comment by ghost** [comment]
Yeah, i will join it

**Comment by ghost** [comment]
What's the link?

**Comment by Alphalaneous** [comment]
https://discord.gg/x2awccH

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
i joined
